# Generated by Django 2.0.13 on 2019-05-14 23:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(verbose_name='Descricao')),
            ],
        ),
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('campus', models.CharField(max_length=150, verbose_name='Escola')),
                ('course', models.CharField(max_length=150, verbose_name='Curso')),
                ('location', models.CharField(max_length=80, verbose_name='Local')),
                ('period', models.CharField(max_length=80, verbose_name='Periodo')),
                ('description', models.TextField(verbose_name='Descricao')),
            ],
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Nome')),
                ('Idiom', models.CharField(max_length=80, verbose_name='Idioma')),
                ('period', models.CharField(max_length=80, verbose_name='Periodo')),
            ],
        ),
        migrations.CreateModel(
            name='Objective',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=200, verbose_name='Objetivo')),
            ],
        ),
        migrations.CreateModel(
            name='PersonalData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='Nome')),
                ('address', models.CharField(max_length=150, verbose_name='Endereco')),
                ('email', models.EmailField(max_length=120, verbose_name='Email')),
                ('phone', models.CharField(max_length=80, verbose_name='Telefone')),
                ('url_Linkedin', models.URLField(max_length=80, verbose_name='LinkedIn')),
                ('age', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ProfessionalExperience',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(max_length=150, verbose_name='Empresa')),
                ('post', models.CharField(max_length=80, verbose_name='Cargo')),
                ('location', models.CharField(max_length=80, verbose_name='Local')),
                ('period', models.CharField(max_length=80, verbose_name='Periodo')),
                ('description', models.TextField(verbose_name='Descricao')),
            ],
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(verbose_name='Descricao')),
            ],
        ),
    ]
